// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZOKOo5bYOfrexixRCGETav2PBIfexj5E',
    appId: '1:148430841970:web:fc4cb9ddcacfb0e2c43aeb',
    messagingSenderId: '148430841970',
    projectId: 'notesapp-39bda',
    authDomain: 'notesapp-39bda.firebaseapp.com',
    storageBucket: 'notesapp-39bda.firebasestorage.app',
    measurementId: 'G-GLN3F89YKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcKTmDgRLADIxYYLUKJTPxJvNznRWZTfc',
    appId: '1:148430841970:android:e2a6af2723382f12c43aeb',
    messagingSenderId: '148430841970',
    projectId: 'notesapp-39bda',
    storageBucket: 'notesapp-39bda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaEFivFE_CSjFafVn2Km8PyVjzcNKeftg',
    appId: '1:148430841970:ios:04215fa8b3d19a8dc43aeb',
    messagingSenderId: '148430841970',
    projectId: 'notesapp-39bda',
    storageBucket: 'notesapp-39bda.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaEFivFE_CSjFafVn2Km8PyVjzcNKeftg',
    appId: '1:148430841970:ios:04215fa8b3d19a8dc43aeb',
    messagingSenderId: '148430841970',
    projectId: 'notesapp-39bda',
    storageBucket: 'notesapp-39bda.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZOKOo5bYOfrexixRCGETav2PBIfexj5E',
    appId: '1:148430841970:web:79c8df5b5b2ade32c43aeb',
    messagingSenderId: '148430841970',
    projectId: 'notesapp-39bda',
    authDomain: 'notesapp-39bda.firebaseapp.com',
    storageBucket: 'notesapp-39bda.firebasestorage.app',
    measurementId: 'G-MD7JMNX9H9',
  );
}
